
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.addie.aitplus.init;

import net.minecraft.world.level.block.Block;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.Registry;

import net.addie.aitplus.block.TrenzalorianStoneWallBlock;
import net.addie.aitplus.block.TrenzalorianStoneStairsBlock;
import net.addie.aitplus.block.TrenzalorianStoneSlabBlock;
import net.addie.aitplus.block.TrenzalorianStoneBlock;
import net.addie.aitplus.block.ToyotaBookshelfBlock;
import net.addie.aitplus.block.ThalmaTrapdoorBlock;
import net.addie.aitplus.block.ThalmaStairsBlock;
import net.addie.aitplus.block.ThalmaSlabBlock;
import net.addie.aitplus.block.ThalmaPressurePlateBlock;
import net.addie.aitplus.block.ThalmaPlanksBlock;
import net.addie.aitplus.block.ThalmaLogBlock;
import net.addie.aitplus.block.ThalmaLeavesBlock;
import net.addie.aitplus.block.ThalmaFenceGateBlock;
import net.addie.aitplus.block.ThalmaFenceBlock;
import net.addie.aitplus.block.ThalmaDoorBlock;
import net.addie.aitplus.block.ThalmaButtonBlock;
import net.addie.aitplus.block.ThalmaBlock;
import net.addie.aitplus.block.StrippedWarpedStemStainedRoundelBlock;
import net.addie.aitplus.block.StrippedThalmaWoodBlock;
import net.addie.aitplus.block.StrippedThalmaLogBlock;
import net.addie.aitplus.block.StrippedSpruceLogStainedRoundelBlock;
import net.addie.aitplus.block.StrippedOakLogStainedRoundelBlock;
import net.addie.aitplus.block.StrippedMangroveLogStainedRoundelBlock;
import net.addie.aitplus.block.StrippedMaldorWoodBlock;
import net.addie.aitplus.block.StrippedMaldorLogBlock;
import net.addie.aitplus.block.StrippedJungleLogStainedRoundelBlock;
import net.addie.aitplus.block.StrippedDarkOakLogStainedRoundelBlock;
import net.addie.aitplus.block.StrippedCrimsonStemStainedRoundelBlock;
import net.addie.aitplus.block.StrippedCherryLogStainedRoundelBlock;
import net.addie.aitplus.block.StrippedBirchLogStainedRoundelBlock;
import net.addie.aitplus.block.StrippedBambooBlockStainedRoundelBlock;
import net.addie.aitplus.block.StrippedAcaciaLogStainedRoundelBlock;
import net.addie.aitplus.block.StreetLampBlock;
import net.addie.aitplus.block.StoneDoorBlock;
import net.addie.aitplus.block.StoneBricksStainedRoundelBlock;
import net.addie.aitplus.block.Statue1Block;
import net.addie.aitplus.block.SealOfRassilonBlock;
import net.addie.aitplus.block.SchlenkBlossomsBlock;
import net.addie.aitplus.block.RoundelTableBlock;
import net.addie.aitplus.block.RetroDoorBlock;
import net.addie.aitplus.block.RetroBBlock;
import net.addie.aitplus.block.RetroABlock;
import net.addie.aitplus.block.RedPetaledOrchidBlock;
import net.addie.aitplus.block.QuartzRoundelBlock;
import net.addie.aitplus.block.QuartzDoorBlock;
import net.addie.aitplus.block.QuartzBlockStainedRoundelBlock;
import net.addie.aitplus.block.QuartzBBlock;
import net.addie.aitplus.block.PolishedBlackstoneStainedRoundelBlock;
import net.addie.aitplus.block.MoonlightBloomBlock;
import net.addie.aitplus.block.MetalGrateWallBlock;
import net.addie.aitplus.block.MetalGrateStairsBlock;
import net.addie.aitplus.block.MetalGrateSlabBlock;
import net.addie.aitplus.block.MetalGrateBlock;
import net.addie.aitplus.block.MaldorWoodBlock;
import net.addie.aitplus.block.MaldorTrapDoorBlock;
import net.addie.aitplus.block.MaldorStairsBlock;
import net.addie.aitplus.block.MaldorSlabBlock;
import net.addie.aitplus.block.MaldorPressurePlateBlock;
import net.addie.aitplus.block.MaldorPlanksBlock;
import net.addie.aitplus.block.MaldorLogBlock;
import net.addie.aitplus.block.MaldorLeavesBlock;
import net.addie.aitplus.block.MaldorFenceGateBlock;
import net.addie.aitplus.block.MaldorFenceBlock;
import net.addie.aitplus.block.MaldorDoorBlock;
import net.addie.aitplus.block.MaldorButtonBlock;
import net.addie.aitplus.block.LEDRoundelYellowBlock;
import net.addie.aitplus.block.LEDRoundelRedBlock;
import net.addie.aitplus.block.LEDRoundelPurpleBlock;
import net.addie.aitplus.block.LEDRoundelPinkBlock;
import net.addie.aitplus.block.LEDRoundelOrangeBlock;
import net.addie.aitplus.block.LEDRoundelGreenBlock;
import net.addie.aitplus.block.LEDRoundelGrayBlock;
import net.addie.aitplus.block.LEDRoundelCyanBlock;
import net.addie.aitplus.block.LEDRoundelBlueBlock;
import net.addie.aitplus.block.LEDRoundelBlock;
import net.addie.aitplus.block.LEDRoundelBlackBlock;
import net.addie.aitplus.block.JukeboxTopBlock;
import net.addie.aitplus.block.IridescentVelvetRedMadeviniaAridosaBlock;
import net.addie.aitplus.block.HatStandWhiteBlock;
import net.addie.aitplus.block.HatStandBlock;
import net.addie.aitplus.block.GramophoneBlock;
import net.addie.aitplus.block.FlowerOfRemeberanceBlock;
import net.addie.aitplus.block.DalekaniumOreBlock;
import net.addie.aitplus.block.CandleStandBlock;
import net.addie.aitplus.block.CandelStandLitBlock;
import net.addie.aitplus.block.BrachackiDoorBlock;
import net.addie.aitplus.block.BrachackiBBlock;
import net.addie.aitplus.block.BrachackiABlock;
import net.addie.aitplus.block.BowlBBlock;
import net.addie.aitplus.block.BowlABlock;
import net.addie.aitplus.block.BlockOfRawDalekaniumBlock;
import net.addie.aitplus.block.BlockOfDalekaniumBlock;
import net.addie.aitplus.block.BlockOfBrachackiBlock;
import net.addie.aitplus.block.ArkytiorBlock;
import net.addie.aitplus.AitplusMod;

public class AitplusModBlocks {
	public static Block TRENZALORIAN_STONE;
	public static Block TRENZALORIAN_STONE_STAIRS;
	public static Block TRENZALORIAN_STONE_SLAB;
	public static Block TRENZALORIAN_STONE_WALL;
	public static Block THALMA_LOG;
	public static Block THALMA_WOOD;
	public static Block STRIPPED_THALMA_LOG;
	public static Block STRIPPED_THALMA_WOOD;
	public static Block THALMA_PLANKS;
	public static Block THALMA_STAIRS;
	public static Block THALMA_SLAB;
	public static Block THALMA_FENCE;
	public static Block THALMA_FENCE_GATE;
	public static Block THALMA_DOOR;
	public static Block THALMA_TRAPDOOR;
	public static Block THALMA_BUTTON;
	public static Block THALMA_PRESSURE_PLATE;
	public static Block THALMA_LEAVES;
	public static Block MALDOR_LOG;
	public static Block MALDOR_WOOD;
	public static Block STRIPPED_MALDOR_LOG;
	public static Block STRIPPED_MALDOR_WOOD;
	public static Block MALDOR_PLANKS;
	public static Block MALDOR_STAIRS;
	public static Block MALDOR_SLAB;
	public static Block MALDOR_TRAP_DOOR;
	public static Block MALDOR_DOOR;
	public static Block MALDOR_PRESSURE_PLATE;
	public static Block MALDOR_BUTTON;
	public static Block MALDOR_FENCE;
	public static Block MALDOR_FENCE_GATE;
	public static Block MALDOR_LEAVES;
	public static Block METAL_GRATE;
	public static Block METAL_GRATE_STAIRS;
	public static Block METAL_GRATE_SLAB;
	public static Block METAL_GRATE_WALL;
	public static Block DALEKANIUM_ORE;
	public static Block BLOCK_OF_DALEKANIUM;
	public static Block BLOCK_OF_RAW_DALEKANIUM;
	public static Block LED_ROUNDEL;
	public static Block BLOCK_OF_BRACHACKI;
	public static Block BRACHACKI_A;
	public static Block BRACHACKI_B;
	public static Block BRACHACKI_DOOR;
	public static Block RETRO_A;
	public static Block RETRO_B;
	public static Block RETRO_DOOR;
	public static Block QUARTZ_A;
	public static Block QUARTZ_B;
	public static Block QUARTZ_DOOR;
	public static Block STRIPPED_DARK_OAK_LOG_STAINED_ROUNDEL;
	public static Block STRIPPED_JUNGLE_LOG_STAINED_ROUNDEL;
	public static Block STRIPPED_SPRUCE_LOG_STAINED_ROUNDEL;
	public static Block STRIPPED_OAK_LOG_STAINED_ROUNDEL;
	public static Block STRIPPED_MANGROVE_LOG_STAINED_ROUNDEL;
	public static Block STRIPPED_WARPED_STEM_STAINED_ROUNDEL;
	public static Block STRIPPED_ACACIA_LOG_STAINED_ROUNDEL;
	public static Block STRIPPED_BAMBOO_BLOCK_STAINED_ROUNDEL;
	public static Block STRIPPED_CHERRY_LOG_STAINED_ROUNDEL;
	public static Block STRIPPED_BIRCH_LOG_STAINED_ROUNDEL;
	public static Block STRIPPED_CRIMSON_STEM_STAINED_ROUNDEL;
	public static Block STONE_BRICKS_STAINED_ROUNDEL;
	public static Block POLISHED_BLACKSTONE_STAINED_ROUNDEL;
	public static Block QUARTZ_BLOCK_STAINED_ROUNDEL;
	public static Block BOWL_A;
	public static Block BOWL_B;
	public static Block STONE_DOOR;
	public static Block ARKYTIOR;
	public static Block FLOWER_OF_REMEBERANCE;
	public static Block IRIDESCENT_VELVET_RED_MADEVINIA_ARIDOSA;
	public static Block MOONLIGHT_BLOOM;
	public static Block RED_PETALED_ORCHID;
	public static Block SCHLENK_BLOSSOMS;
	public static Block HAT_STAND;
	public static Block HAT_STAND_WHITE;
	public static Block STATUE_1;
	public static Block GRAMOPHONE;
	public static Block CANDLE_STAND;
	public static Block JUKEBOX_TOP;
	public static Block TOYOTA_BOOKSHELF;
	public static Block SEAL_OF_RASSILON;
	public static Block STREET_LAMP;
	public static Block LED_ROUNDEL_BLACK;
	public static Block LED_ROUNDEL_BLUE;
	public static Block LED_ROUNDEL_CYAN;
	public static Block LED_ROUNDEL_GRAY;
	public static Block LED_ROUNDEL_GREEN;
	public static Block LED_ROUNDEL_ORANGE;
	public static Block LED_ROUNDEL_PINK;
	public static Block LED_ROUNDEL_PURPLE;
	public static Block LED_ROUNDEL_RED;
	public static Block LED_ROUNDEL_YELLOW;
	public static Block ROUNDEL_TABLE;
	public static Block CANDEL_STAND_LIT;

	public static void load() {
		TRENZALORIAN_STONE = register("trenzalorian_stone", new TrenzalorianStoneBlock());
		TRENZALORIAN_STONE_STAIRS = register("trenzalorian_stone_stairs", new TrenzalorianStoneStairsBlock());
		TRENZALORIAN_STONE_SLAB = register("trenzalorian_stone_slab", new TrenzalorianStoneSlabBlock());
		TRENZALORIAN_STONE_WALL = register("trenzalorian_stone_wall", new TrenzalorianStoneWallBlock());
		THALMA_LOG = register("thalma_log", new ThalmaBlock());
		THALMA_WOOD = register("thalma_wood", new ThalmaLogBlock());
		STRIPPED_THALMA_LOG = register("stripped_thalma_log", new StrippedThalmaWoodBlock());
		STRIPPED_THALMA_WOOD = register("stripped_thalma_wood", new StrippedThalmaLogBlock());
		THALMA_PLANKS = register("thalma_planks", new ThalmaPlanksBlock());
		THALMA_STAIRS = register("thalma_stairs", new ThalmaStairsBlock());
		THALMA_SLAB = register("thalma_slab", new ThalmaSlabBlock());
		THALMA_FENCE = register("thalma_fence", new ThalmaFenceBlock());
		THALMA_FENCE_GATE = register("thalma_fence_gate", new ThalmaFenceGateBlock());
		THALMA_DOOR = register("thalma_door", new ThalmaDoorBlock());
		THALMA_TRAPDOOR = register("thalma_trapdoor", new ThalmaTrapdoorBlock());
		THALMA_BUTTON = register("thalma_button", new ThalmaButtonBlock());
		THALMA_PRESSURE_PLATE = register("thalma_pressure_plate", new ThalmaPressurePlateBlock());
		THALMA_LEAVES = register("thalma_leaves", new ThalmaLeavesBlock());
		MALDOR_LOG = register("maldor_log", new MaldorLogBlock());
		MALDOR_WOOD = register("maldor_wood", new MaldorWoodBlock());
		STRIPPED_MALDOR_LOG = register("stripped_maldor_log", new StrippedMaldorLogBlock());
		STRIPPED_MALDOR_WOOD = register("stripped_maldor_wood", new StrippedMaldorWoodBlock());
		MALDOR_PLANKS = register("maldor_planks", new MaldorPlanksBlock());
		MALDOR_STAIRS = register("maldor_stairs", new MaldorStairsBlock());
		MALDOR_SLAB = register("maldor_slab", new MaldorSlabBlock());
		MALDOR_TRAP_DOOR = register("maldor_trap_door", new MaldorTrapDoorBlock());
		MALDOR_DOOR = register("maldor_door", new MaldorDoorBlock());
		MALDOR_PRESSURE_PLATE = register("maldor_pressure_plate", new MaldorPressurePlateBlock());
		MALDOR_BUTTON = register("maldor_button", new MaldorButtonBlock());
		MALDOR_FENCE = register("maldor_fence", new MaldorFenceBlock());
		MALDOR_FENCE_GATE = register("maldor_fence_gate", new MaldorFenceGateBlock());
		MALDOR_LEAVES = register("maldor_leaves", new MaldorLeavesBlock());
		METAL_GRATE = register("metal_grate", new MetalGrateBlock());
		METAL_GRATE_STAIRS = register("metal_grate_stairs", new MetalGrateStairsBlock());
		METAL_GRATE_SLAB = register("metal_grate_slab", new MetalGrateSlabBlock());
		METAL_GRATE_WALL = register("metal_grate_wall", new MetalGrateWallBlock());
		DALEKANIUM_ORE = register("dalekanium_ore", new DalekaniumOreBlock());
		BLOCK_OF_DALEKANIUM = register("block_of_dalekanium", new BlockOfDalekaniumBlock());
		BLOCK_OF_RAW_DALEKANIUM = register("block_of_raw_dalekanium", new BlockOfRawDalekaniumBlock());
		LED_ROUNDEL = register("led_roundel", new LEDRoundelBlock());
		BLOCK_OF_BRACHACKI = register("block_of_brachacki", new BlockOfBrachackiBlock());
		BRACHACKI_A = register("brachacki_a", new BrachackiABlock());
		BRACHACKI_B = register("brachacki_b", new BrachackiBBlock());
		BRACHACKI_DOOR = register("brachacki_door", new BrachackiDoorBlock());
		RETRO_A = register("retro_a", new RetroABlock());
		RETRO_B = register("retro_b", new RetroBBlock());
		RETRO_DOOR = register("retro_door", new RetroDoorBlock());
		QUARTZ_A = register("quartz_a", new QuartzRoundelBlock());
		QUARTZ_B = register("quartz_b", new QuartzBBlock());
		QUARTZ_DOOR = register("quartz_door", new QuartzDoorBlock());
		STRIPPED_DARK_OAK_LOG_STAINED_ROUNDEL = register("stripped_dark_oak_log_stained_roundel", new StrippedDarkOakLogStainedRoundelBlock());
		STRIPPED_JUNGLE_LOG_STAINED_ROUNDEL = register("stripped_jungle_log_stained_roundel", new StrippedJungleLogStainedRoundelBlock());
		STRIPPED_SPRUCE_LOG_STAINED_ROUNDEL = register("stripped_spruce_log_stained_roundel", new StrippedSpruceLogStainedRoundelBlock());
		STRIPPED_OAK_LOG_STAINED_ROUNDEL = register("stripped_oak_log_stained_roundel", new StrippedOakLogStainedRoundelBlock());
		STRIPPED_MANGROVE_LOG_STAINED_ROUNDEL = register("stripped_mangrove_log_stained_roundel", new StrippedMangroveLogStainedRoundelBlock());
		STRIPPED_WARPED_STEM_STAINED_ROUNDEL = register("stripped_warped_stem_stained_roundel", new StrippedWarpedStemStainedRoundelBlock());
		STRIPPED_ACACIA_LOG_STAINED_ROUNDEL = register("stripped_acacia_log_stained_roundel", new StrippedAcaciaLogStainedRoundelBlock());
		STRIPPED_BAMBOO_BLOCK_STAINED_ROUNDEL = register("stripped_bamboo_block_stained_roundel", new StrippedBambooBlockStainedRoundelBlock());
		STRIPPED_CHERRY_LOG_STAINED_ROUNDEL = register("stripped_cherry_log_stained_roundel", new StrippedCherryLogStainedRoundelBlock());
		STRIPPED_BIRCH_LOG_STAINED_ROUNDEL = register("stripped_birch_log_stained_roundel", new StrippedBirchLogStainedRoundelBlock());
		STRIPPED_CRIMSON_STEM_STAINED_ROUNDEL = register("stripped_crimson_stem_stained_roundel", new StrippedCrimsonStemStainedRoundelBlock());
		STONE_BRICKS_STAINED_ROUNDEL = register("stone_bricks_stained_roundel", new StoneBricksStainedRoundelBlock());
		POLISHED_BLACKSTONE_STAINED_ROUNDEL = register("polished_blackstone_stained_roundel", new PolishedBlackstoneStainedRoundelBlock());
		QUARTZ_BLOCK_STAINED_ROUNDEL = register("quartz_block_stained_roundel", new QuartzBlockStainedRoundelBlock());
		BOWL_A = register("bowl_a", new BowlABlock());
		BOWL_B = register("bowl_b", new BowlBBlock());
		STONE_DOOR = register("stone_door", new StoneDoorBlock());
		ARKYTIOR = register("arkytior", new ArkytiorBlock());
		FLOWER_OF_REMEBERANCE = register("flower_of_remeberance", new FlowerOfRemeberanceBlock());
		IRIDESCENT_VELVET_RED_MADEVINIA_ARIDOSA = register("iridescent_velvet_red_madevinia_aridosa", new IridescentVelvetRedMadeviniaAridosaBlock());
		MOONLIGHT_BLOOM = register("moonlight_bloom", new MoonlightBloomBlock());
		RED_PETALED_ORCHID = register("red_petaled_orchid", new RedPetaledOrchidBlock());
		SCHLENK_BLOSSOMS = register("schlenk_blossoms", new SchlenkBlossomsBlock());
		HAT_STAND = register("hat_stand", new HatStandBlock());
		HAT_STAND_WHITE = register("hat_stand_white", new HatStandWhiteBlock());
		STATUE_1 = register("statue_1", new Statue1Block());
		GRAMOPHONE = register("gramophone", new GramophoneBlock());
		CANDLE_STAND = register("candle_stand", new CandleStandBlock());
		JUKEBOX_TOP = register("jukebox_top", new JukeboxTopBlock());
		TOYOTA_BOOKSHELF = register("toyota_bookshelf", new ToyotaBookshelfBlock());
		SEAL_OF_RASSILON = register("seal_of_rassilon", new SealOfRassilonBlock());
		STREET_LAMP = register("street_lamp", new StreetLampBlock());
		LED_ROUNDEL_BLACK = register("led_roundel_black", new LEDRoundelBlackBlock());
		LED_ROUNDEL_BLUE = register("led_roundel_blue", new LEDRoundelBlueBlock());
		LED_ROUNDEL_CYAN = register("led_roundel_cyan", new LEDRoundelCyanBlock());
		LED_ROUNDEL_GRAY = register("led_roundel_gray", new LEDRoundelGrayBlock());
		LED_ROUNDEL_GREEN = register("led_roundel_green", new LEDRoundelGreenBlock());
		LED_ROUNDEL_ORANGE = register("led_roundel_orange", new LEDRoundelOrangeBlock());
		LED_ROUNDEL_PINK = register("led_roundel_pink", new LEDRoundelPinkBlock());
		LED_ROUNDEL_PURPLE = register("led_roundel_purple", new LEDRoundelPurpleBlock());
		LED_ROUNDEL_RED = register("led_roundel_red", new LEDRoundelRedBlock());
		LED_ROUNDEL_YELLOW = register("led_roundel_yellow", new LEDRoundelYellowBlock());
		ROUNDEL_TABLE = register("roundel_table", new RoundelTableBlock());
		CANDEL_STAND_LIT = register("candel_stand_lit", new CandelStandLitBlock());
	}

	public static void clientLoad() {
		TrenzalorianStoneBlock.clientInit();
		TrenzalorianStoneStairsBlock.clientInit();
		TrenzalorianStoneSlabBlock.clientInit();
		TrenzalorianStoneWallBlock.clientInit();
		ThalmaBlock.clientInit();
		ThalmaLogBlock.clientInit();
		StrippedThalmaWoodBlock.clientInit();
		StrippedThalmaLogBlock.clientInit();
		ThalmaPlanksBlock.clientInit();
		ThalmaStairsBlock.clientInit();
		ThalmaSlabBlock.clientInit();
		ThalmaFenceBlock.clientInit();
		ThalmaFenceGateBlock.clientInit();
		ThalmaDoorBlock.clientInit();
		ThalmaTrapdoorBlock.clientInit();
		ThalmaButtonBlock.clientInit();
		ThalmaPressurePlateBlock.clientInit();
		ThalmaLeavesBlock.clientInit();
		MaldorLogBlock.clientInit();
		MaldorWoodBlock.clientInit();
		StrippedMaldorLogBlock.clientInit();
		StrippedMaldorWoodBlock.clientInit();
		MaldorPlanksBlock.clientInit();
		MaldorStairsBlock.clientInit();
		MaldorSlabBlock.clientInit();
		MaldorTrapDoorBlock.clientInit();
		MaldorDoorBlock.clientInit();
		MaldorPressurePlateBlock.clientInit();
		MaldorButtonBlock.clientInit();
		MaldorFenceBlock.clientInit();
		MaldorFenceGateBlock.clientInit();
		MaldorLeavesBlock.clientInit();
		MetalGrateBlock.clientInit();
		MetalGrateStairsBlock.clientInit();
		MetalGrateSlabBlock.clientInit();
		MetalGrateWallBlock.clientInit();
		DalekaniumOreBlock.clientInit();
		BlockOfDalekaniumBlock.clientInit();
		BlockOfRawDalekaniumBlock.clientInit();
		LEDRoundelBlock.clientInit();
		BlockOfBrachackiBlock.clientInit();
		BrachackiABlock.clientInit();
		BrachackiBBlock.clientInit();
		BrachackiDoorBlock.clientInit();
		RetroABlock.clientInit();
		RetroBBlock.clientInit();
		RetroDoorBlock.clientInit();
		QuartzRoundelBlock.clientInit();
		QuartzBBlock.clientInit();
		QuartzDoorBlock.clientInit();
		StrippedDarkOakLogStainedRoundelBlock.clientInit();
		StrippedJungleLogStainedRoundelBlock.clientInit();
		StrippedSpruceLogStainedRoundelBlock.clientInit();
		StrippedOakLogStainedRoundelBlock.clientInit();
		StrippedMangroveLogStainedRoundelBlock.clientInit();
		StrippedWarpedStemStainedRoundelBlock.clientInit();
		StrippedAcaciaLogStainedRoundelBlock.clientInit();
		StrippedBambooBlockStainedRoundelBlock.clientInit();
		StrippedCherryLogStainedRoundelBlock.clientInit();
		StrippedBirchLogStainedRoundelBlock.clientInit();
		StrippedCrimsonStemStainedRoundelBlock.clientInit();
		StoneBricksStainedRoundelBlock.clientInit();
		PolishedBlackstoneStainedRoundelBlock.clientInit();
		QuartzBlockStainedRoundelBlock.clientInit();
		BowlABlock.clientInit();
		BowlBBlock.clientInit();
		StoneDoorBlock.clientInit();
		ArkytiorBlock.clientInit();
		FlowerOfRemeberanceBlock.clientInit();
		IridescentVelvetRedMadeviniaAridosaBlock.clientInit();
		MoonlightBloomBlock.clientInit();
		RedPetaledOrchidBlock.clientInit();
		SchlenkBlossomsBlock.clientInit();
		HatStandBlock.clientInit();
		HatStandWhiteBlock.clientInit();
		Statue1Block.clientInit();
		GramophoneBlock.clientInit();
		CandleStandBlock.clientInit();
		JukeboxTopBlock.clientInit();
		ToyotaBookshelfBlock.clientInit();
		SealOfRassilonBlock.clientInit();
		StreetLampBlock.clientInit();
		LEDRoundelBlackBlock.clientInit();
		LEDRoundelBlueBlock.clientInit();
		LEDRoundelCyanBlock.clientInit();
		LEDRoundelGrayBlock.clientInit();
		LEDRoundelGreenBlock.clientInit();
		LEDRoundelOrangeBlock.clientInit();
		LEDRoundelPinkBlock.clientInit();
		LEDRoundelPurpleBlock.clientInit();
		LEDRoundelRedBlock.clientInit();
		LEDRoundelYellowBlock.clientInit();
		RoundelTableBlock.clientInit();
		CandelStandLitBlock.clientInit();
	}

	private static Block register(String registryName, Block block) {
		return Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AitplusMod.MODID, registryName), block);
	}
}
