
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.addie.aitplus.init;

import net.minecraft.world.level.block.Block;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.Registry;

import net.addie.aitplus.block.TrenzalorianStoneWallBlock;
import net.addie.aitplus.block.TrenzalorianStoneStairsBlock;
import net.addie.aitplus.block.TrenzalorianStoneSlabBlock;
import net.addie.aitplus.block.TrenzalorianStoneBlock;
import net.addie.aitplus.block.ThalmaTrapdoorBlock;
import net.addie.aitplus.block.ThalmaStairsBlock;
import net.addie.aitplus.block.ThalmaSlabBlock;
import net.addie.aitplus.block.ThalmaPressurePlateBlock;
import net.addie.aitplus.block.ThalmaPlanksBlock;
import net.addie.aitplus.block.ThalmaLogBlock;
import net.addie.aitplus.block.ThalmaLeavesBlock;
import net.addie.aitplus.block.ThalmaFenceGateBlock;
import net.addie.aitplus.block.ThalmaFenceBlock;
import net.addie.aitplus.block.ThalmaDoorBlock;
import net.addie.aitplus.block.ThalmaButtonBlock;
import net.addie.aitplus.block.ThalmaBlock;
import net.addie.aitplus.block.StrippedThalmaWoodBlock;
import net.addie.aitplus.block.StrippedThalmaLogBlock;
import net.addie.aitplus.block.StrippedMaldorWoodBlock;
import net.addie.aitplus.block.StrippedMaldorLogBlock;
import net.addie.aitplus.block.SchlenkBlossomsBlock;
import net.addie.aitplus.block.RedPetaledOrchidBlock;
import net.addie.aitplus.block.MoonlightBloomBlock;
import net.addie.aitplus.block.MetalGrateWallBlock;
import net.addie.aitplus.block.MetalGrateStairsBlock;
import net.addie.aitplus.block.MetalGrateSlabBlock;
import net.addie.aitplus.block.MetalGrateBlock;
import net.addie.aitplus.block.MaldorWoodBlock;
import net.addie.aitplus.block.MaldorTrapDoorBlock;
import net.addie.aitplus.block.MaldorStairsBlock;
import net.addie.aitplus.block.MaldorSlabBlock;
import net.addie.aitplus.block.MaldorPressurePlateBlock;
import net.addie.aitplus.block.MaldorPlanksBlock;
import net.addie.aitplus.block.MaldorLogBlock;
import net.addie.aitplus.block.MaldorLeavesBlock;
import net.addie.aitplus.block.MaldorFenceGateBlock;
import net.addie.aitplus.block.MaldorFenceBlock;
import net.addie.aitplus.block.MaldorDoorBlock;
import net.addie.aitplus.block.MaldorButtonBlock;
import net.addie.aitplus.block.LEDRoundelYellowBlock;
import net.addie.aitplus.block.LEDRoundelRedBlock;
import net.addie.aitplus.block.LEDRoundelPurpleBlock;
import net.addie.aitplus.block.LEDRoundelPinkBlock;
import net.addie.aitplus.block.LEDRoundelOrangeBlock;
import net.addie.aitplus.block.LEDRoundelGreenBlock;
import net.addie.aitplus.block.LEDRoundelGrayBlock;
import net.addie.aitplus.block.LEDRoundelCyanBlock;
import net.addie.aitplus.block.LEDRoundelBlueBlock;
import net.addie.aitplus.block.LEDRoundelBlock;
import net.addie.aitplus.block.LEDRoundelBlackBlock;
import net.addie.aitplus.block.IridescentVelvetRedMadeviniaAridosaBlock;
import net.addie.aitplus.block.FlowerOfRemeberanceBlock;
import net.addie.aitplus.block.ArkytiorBlock;
import net.addie.aitplus.AitplusMod;

public class AitplusModBlocks {
	public static Block TRENZALORIAN_STONE;
	public static Block TRENZALORIAN_STONE_STAIRS;
	public static Block TRENZALORIAN_STONE_SLAB;
	public static Block TRENZALORIAN_STONE_WALL;
	public static Block THALMA_LOG;
	public static Block THALMA_WOOD;
	public static Block STRIPPED_THALMA_LOG;
	public static Block STRIPPED_THALMA_WOOD;
	public static Block THALMA_PLANKS;
	public static Block THALMA_STAIRS;
	public static Block THALMA_SLAB;
	public static Block THALMA_FENCE;
	public static Block THALMA_FENCE_GATE;
	public static Block THALMA_DOOR;
	public static Block THALMA_TRAPDOOR;
	public static Block THALMA_BUTTON;
	public static Block THALMA_PRESSURE_PLATE;
	public static Block THALMA_LEAVES;
	public static Block MALDOR_LOG;
	public static Block MALDOR_WOOD;
	public static Block STRIPPED_MALDOR_LOG;
	public static Block STRIPPED_MALDOR_WOOD;
	public static Block MALDOR_PLANKS;
	public static Block MALDOR_STAIRS;
	public static Block MALDOR_SLAB;
	public static Block MALDOR_TRAP_DOOR;
	public static Block MALDOR_DOOR;
	public static Block MALDOR_PRESSURE_PLATE;
	public static Block MALDOR_BUTTON;
	public static Block MALDOR_FENCE;
	public static Block MALDOR_FENCE_GATE;
	public static Block MALDOR_LEAVES;
	public static Block LED_ROUNDEL;
	public static Block METAL_GRATE;
	public static Block METAL_GRATE_STAIRS;
	public static Block METAL_GRATE_SLAB;
	public static Block METAL_GRATE_WALL;
	public static Block ARKYTIOR;
	public static Block FLOWER_OF_REMEBERANCE;
	public static Block IRIDESCENT_VELVET_RED_MADEVINIA_ARIDOSA;
	public static Block MOONLIGHT_BLOOM;
	public static Block RED_PETALED_ORCHID;
	public static Block SCHLENK_BLOSSOMS;
	public static Block LED_ROUNDEL_BLACK;
	public static Block LED_ROUNDEL_BLUE;
	public static Block LED_ROUNDEL_CYAN;
	public static Block LED_ROUNDEL_GRAY;
	public static Block LED_ROUNDEL_GREEN;
	public static Block LED_ROUNDEL_ORANGE;
	public static Block LED_ROUNDEL_PINK;
	public static Block LED_ROUNDEL_PURPLE;
	public static Block LED_ROUNDEL_RED;
	public static Block LED_ROUNDEL_YELLOW;

	public static void load() {
		TRENZALORIAN_STONE = register("trenzalorian_stone", new TrenzalorianStoneBlock());
		TRENZALORIAN_STONE_STAIRS = register("trenzalorian_stone_stairs", new TrenzalorianStoneStairsBlock());
		TRENZALORIAN_STONE_SLAB = register("trenzalorian_stone_slab", new TrenzalorianStoneSlabBlock());
		TRENZALORIAN_STONE_WALL = register("trenzalorian_stone_wall", new TrenzalorianStoneWallBlock());
		THALMA_LOG = register("thalma_log", new ThalmaBlock());
		THALMA_WOOD = register("thalma_wood", new ThalmaLogBlock());
		STRIPPED_THALMA_LOG = register("stripped_thalma_log", new StrippedThalmaWoodBlock());
		STRIPPED_THALMA_WOOD = register("stripped_thalma_wood", new StrippedThalmaLogBlock());
		THALMA_PLANKS = register("thalma_planks", new ThalmaPlanksBlock());
		THALMA_STAIRS = register("thalma_stairs", new ThalmaStairsBlock());
		THALMA_SLAB = register("thalma_slab", new ThalmaSlabBlock());
		THALMA_FENCE = register("thalma_fence", new ThalmaFenceBlock());
		THALMA_FENCE_GATE = register("thalma_fence_gate", new ThalmaFenceGateBlock());
		THALMA_DOOR = register("thalma_door", new ThalmaDoorBlock());
		THALMA_TRAPDOOR = register("thalma_trapdoor", new ThalmaTrapdoorBlock());
		THALMA_BUTTON = register("thalma_button", new ThalmaButtonBlock());
		THALMA_PRESSURE_PLATE = register("thalma_pressure_plate", new ThalmaPressurePlateBlock());
		THALMA_LEAVES = register("thalma_leaves", new ThalmaLeavesBlock());
		MALDOR_LOG = register("maldor_log", new MaldorLogBlock());
		MALDOR_WOOD = register("maldor_wood", new MaldorWoodBlock());
		STRIPPED_MALDOR_LOG = register("stripped_maldor_log", new StrippedMaldorLogBlock());
		STRIPPED_MALDOR_WOOD = register("stripped_maldor_wood", new StrippedMaldorWoodBlock());
		MALDOR_PLANKS = register("maldor_planks", new MaldorPlanksBlock());
		MALDOR_STAIRS = register("maldor_stairs", new MaldorStairsBlock());
		MALDOR_SLAB = register("maldor_slab", new MaldorSlabBlock());
		MALDOR_TRAP_DOOR = register("maldor_trap_door", new MaldorTrapDoorBlock());
		MALDOR_DOOR = register("maldor_door", new MaldorDoorBlock());
		MALDOR_PRESSURE_PLATE = register("maldor_pressure_plate", new MaldorPressurePlateBlock());
		MALDOR_BUTTON = register("maldor_button", new MaldorButtonBlock());
		MALDOR_FENCE = register("maldor_fence", new MaldorFenceBlock());
		MALDOR_FENCE_GATE = register("maldor_fence_gate", new MaldorFenceGateBlock());
		MALDOR_LEAVES = register("maldor_leaves", new MaldorLeavesBlock());
		LED_ROUNDEL = register("led_roundel", new LEDRoundelBlock());
		METAL_GRATE = register("metal_grate", new MetalGrateBlock());
		METAL_GRATE_STAIRS = register("metal_grate_stairs", new MetalGrateStairsBlock());
		METAL_GRATE_SLAB = register("metal_grate_slab", new MetalGrateSlabBlock());
		METAL_GRATE_WALL = register("metal_grate_wall", new MetalGrateWallBlock());
		ARKYTIOR = register("arkytior", new ArkytiorBlock());
		FLOWER_OF_REMEBERANCE = register("flower_of_remeberance", new FlowerOfRemeberanceBlock());
		IRIDESCENT_VELVET_RED_MADEVINIA_ARIDOSA = register("iridescent_velvet_red_madevinia_aridosa", new IridescentVelvetRedMadeviniaAridosaBlock());
		MOONLIGHT_BLOOM = register("moonlight_bloom", new MoonlightBloomBlock());
		RED_PETALED_ORCHID = register("red_petaled_orchid", new RedPetaledOrchidBlock());
		SCHLENK_BLOSSOMS = register("schlenk_blossoms", new SchlenkBlossomsBlock());
		LED_ROUNDEL_BLACK = register("led_roundel_black", new LEDRoundelBlackBlock());
		LED_ROUNDEL_BLUE = register("led_roundel_blue", new LEDRoundelBlueBlock());
		LED_ROUNDEL_CYAN = register("led_roundel_cyan", new LEDRoundelCyanBlock());
		LED_ROUNDEL_GRAY = register("led_roundel_gray", new LEDRoundelGrayBlock());
		LED_ROUNDEL_GREEN = register("led_roundel_green", new LEDRoundelGreenBlock());
		LED_ROUNDEL_ORANGE = register("led_roundel_orange", new LEDRoundelOrangeBlock());
		LED_ROUNDEL_PINK = register("led_roundel_pink", new LEDRoundelPinkBlock());
		LED_ROUNDEL_PURPLE = register("led_roundel_purple", new LEDRoundelPurpleBlock());
		LED_ROUNDEL_RED = register("led_roundel_red", new LEDRoundelRedBlock());
		LED_ROUNDEL_YELLOW = register("led_roundel_yellow", new LEDRoundelYellowBlock());
	}

	public static void clientLoad() {
		TrenzalorianStoneBlock.clientInit();
		TrenzalorianStoneStairsBlock.clientInit();
		TrenzalorianStoneSlabBlock.clientInit();
		TrenzalorianStoneWallBlock.clientInit();
		ThalmaBlock.clientInit();
		ThalmaLogBlock.clientInit();
		StrippedThalmaWoodBlock.clientInit();
		StrippedThalmaLogBlock.clientInit();
		ThalmaPlanksBlock.clientInit();
		ThalmaStairsBlock.clientInit();
		ThalmaSlabBlock.clientInit();
		ThalmaFenceBlock.clientInit();
		ThalmaFenceGateBlock.clientInit();
		ThalmaDoorBlock.clientInit();
		ThalmaTrapdoorBlock.clientInit();
		ThalmaButtonBlock.clientInit();
		ThalmaPressurePlateBlock.clientInit();
		ThalmaLeavesBlock.clientInit();
		MaldorLogBlock.clientInit();
		MaldorWoodBlock.clientInit();
		StrippedMaldorLogBlock.clientInit();
		StrippedMaldorWoodBlock.clientInit();
		MaldorPlanksBlock.clientInit();
		MaldorStairsBlock.clientInit();
		MaldorSlabBlock.clientInit();
		MaldorTrapDoorBlock.clientInit();
		MaldorDoorBlock.clientInit();
		MaldorPressurePlateBlock.clientInit();
		MaldorButtonBlock.clientInit();
		MaldorFenceBlock.clientInit();
		MaldorFenceGateBlock.clientInit();
		MaldorLeavesBlock.clientInit();
		LEDRoundelBlock.clientInit();
		MetalGrateBlock.clientInit();
		MetalGrateStairsBlock.clientInit();
		MetalGrateSlabBlock.clientInit();
		MetalGrateWallBlock.clientInit();
		ArkytiorBlock.clientInit();
		FlowerOfRemeberanceBlock.clientInit();
		IridescentVelvetRedMadeviniaAridosaBlock.clientInit();
		MoonlightBloomBlock.clientInit();
		RedPetaledOrchidBlock.clientInit();
		SchlenkBlossomsBlock.clientInit();
		LEDRoundelBlackBlock.clientInit();
		LEDRoundelBlueBlock.clientInit();
		LEDRoundelCyanBlock.clientInit();
		LEDRoundelGrayBlock.clientInit();
		LEDRoundelGreenBlock.clientInit();
		LEDRoundelOrangeBlock.clientInit();
		LEDRoundelPinkBlock.clientInit();
		LEDRoundelPurpleBlock.clientInit();
		LEDRoundelRedBlock.clientInit();
		LEDRoundelYellowBlock.clientInit();
	}

	private static Block register(String registryName, Block block) {
		return Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(AitplusMod.MODID, registryName), block);
	}
}
